//
//  ChatModels.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import QiscusCore

enum Chat
{
    // MARK: Use cases
    
    enum FetchChat
    {
        struct Request
        {
        }
        struct Response
        {
            let comments: [CommentModel]
        }
        struct ViewModel
        {
            let comments: [CommentModel]
        }
    }
    
    enum SendChat
    {
        struct Request
        {
            let message: String
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
