//
//  ChatPresenter.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic
{
    func present(response: Chat.FetchChat.Response)
}

class ChatPresenter: ChatPresentationLogic
{
    weak var viewController: ChatDisplayLogic?
    
    // MARK: Do something
    
    func present(response: Chat.FetchChat.Response)
    {
        let viewModel = Chat.FetchChat.ViewModel(comments: response.comments)
        viewController?.display(viewModel: viewModel)
    }
}
