//
//  ChatInteractor.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import QiscusCore

protocol ChatBusinessLogic
{
    func fetchChats(request: Chat.FetchChat.Request)
}

protocol ChatDataStore
{
    var roomId: String! { get set }
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore
{
    var presenter: ChatPresentationLogic?
    var worker: ChatWorker?
    //var name: String = ""
    var roomId:String!
    
    // MARK: Do something
    
    func fetchChats(request: Chat.FetchChat.Request) {
        QiscusCore.shared.getChatRoomWithMessages(roomId: self.roomId, onSuccess: {room, comments in
            let response = Chat.FetchChat.Response(comments: comments)
            self.presenter?.present(response: response)
        }, onError: {error in
            
        })
    }
}
