//
//  ChatListPresenter.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatListPresentationLogic
{
    func present(response: ChatList.FetchChatList.Response)
    
    
}

class ChatListPresenter: ChatListPresentationLogic
{
    weak var viewController: ChatListDisplayLogic?
    
    // MARK: Do something
    
    func present(response: ChatList.FetchChatList.Response)
    {
        let viewModel = ChatList.FetchChatList.ViewModel(rooms: response.rooms)
        viewController?.display(viewModel: viewModel)
    }
}
