//
//  ChatListModels.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import QiscusCore

enum ChatList
{
    // MARK: Use cases
    
    enum FetchChatList
    {
        struct Request
        {
        }
        struct Response
        {
            let rooms:[RoomModel]
        }
        struct ViewModel
        {
            let rooms:[RoomModel]
        }
    }
    
    enum CreateNewRoom
    {
        struct Request
        {
            let username:String
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
           
        }
    }
}
