//
//  ChatListRouter.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatListRoutingLogic
{
  func routeToChatView(segue: UIStoryboardSegue?)
}

protocol ChatListDataPassing
{
  var dataStore: ChatListDataStore? { get }
}

class ChatListRouter: NSObject, ChatListRoutingLogic, ChatListDataPassing
{
  weak var viewController: ChatListViewController?
  var dataStore: ChatListDataStore?
  
  // MARK: Routing
  
  func routeToChatView(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ChatViewController
      var destinationDS = destinationVC.router!.dataStore!
        
      passDataToChatView(source: dataStore!, destination: &destinationDS)
    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToChatView(source: ChatListViewController, destination: ChatViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToChatView(source: ChatListDataStore, destination: inout ChatDataStore)
  {
    let selectedRow = viewController!.tableView.indexPathForSelectedRow!.row
    let selectedRoomId = source.chatrooms![selectedRow].id
    
    destination.roomId = selectedRoomId
  }
}
