//
//  LoginInteractor.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import QiscusCore

protocol LoginBusinessLogic
{
    func doLogin(request: Login.Login.Request)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doLogin(request: Login.Login.Request)
    {
        QiscusCore.setUser(userId: request.email, userKey: request.password, username:request.email, avatarURL: nil, extras: nil, onSuccess: { (user) in

            let response = Login.Login.Response(errorMessage: nil)
            self.presenter!.presentLogin(response: response)
        }) { (error) in
            let response = Login.Login.Response(errorMessage: error.message)
            self.presenter!.presentLogin(response: response)
        }
    }
}
