//
//  LoginPresenter.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentLogin(response: Login.Login.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
    func presentLogin(response: Login.Login.Response)
    {
      let viewModel = Login.Login.ViewModel(errorMessage:response.errorMessage)
      viewController?.displayLogin(viewModel: viewModel)
    }
}
