//
//  LoginModels.swift
//  TesQiscus
//
//  Created by Fahim Jatmiko on 12/02/20.
//  Copyright (c) 2020 Fahim. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Login
    {
        struct Request
        {
            var email: String
            var password: String
        }
        struct Response
        {
            var errorMessage: String?
        }
        struct ViewModel
        {
            var errorMessage: String?
        }
    }
}
